language: node_js
node_js:
 - "12.4.0"

sudo: true

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng lint
  - ng test -watch false -browsers ChromeHeadless
  - ng build --prod


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on: